version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: dsystem-apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile.develop
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - appnet
    depends_on:
      - cart
  cart:
    container_name: dsystem-cart
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: Cart/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - appnet
    depends_on:
      - rabbitmq
  client:
    container_name: dsystem-client
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: GrpcClient/Dockerfile.develop
    networks:
      - appnet
    depends_on:
      - cart
  suggestions:
    container_name: dsystem-suggestions
    image: ${DOCKER_REGISTRY-}suggestions
    build:
      context: .
      dockerfile: Suggestions/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://+:5002
    networks:
      - appnet
    depends_on:
      - rabbitmq
  rabbitmq:
    image: ${DOCKER_REGISTRY-}rabbitmq
    container_name: dsystem-rabbitmq
    build:
      context: .
      dockerfile: RabbitMQ/Dockerfile
    hostname: dsystem-rabbitmq
    networks:
      - appnet
    ports:
      - 5672:5672
      - 15672:15672


networks:
  appnet: